#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

# use dependencies defined in Modulefile
modulefile

mod 'puppetlabs/stdlib', :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
mod 'puppetlabs/concat', :git => 'git://github.com/puppetlabs/puppetlabs-concat.git'
mod 'puppetlabs/git', :git => 'git://github.com/puppetlabs/puppetlabs-git.git'
mod 'mhuffnagle/curl', :git => 'git://github.com/Element84/puppet-curl.git'
mod 'puppetlabs/apt', :git => 'git://github.com/puppetlabs/puppetlabs-apt.git'
mod 'puppetlabs/vcsrepo', :git => 'git://github.com/puppetlabs/puppetlabs-vcsrepo.git'
mod 'puppetlabs/ntp', :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'
mod 'puppetlabs/firewall', :git => 'git://github.com/puppetlabs/puppetlabs-firewall.git'
mod 'puppetlabs/apache', :git => 'git://github.com/puppetlabs/puppetlabs-apache.git'
mod 'example42/puppi', :git => 'git://github.com/example42/puppi.git'
mod 'example42/php', :git => 'git://github.com/example42/puppet-php.git'
mod 'puppetlabs/mysql', :git => 'git://github.com/puppetlabs/puppetlabs-mysql.git'
